language: node_js
node_js:
  - "node"

branches:
  only:
    - gomix
    - master

# before_install:
#   - npm install -g npm@5

before_script:
  - npm prune

script:
  - npx sync-glitch-cli

notifications:
  email:
    on_failure: always

